version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      - PLAY_HTTP_SECRET_KEY=changeme
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
